### ISSUE TITLE
languages are missing!

### ISSUE THREAD

**Issue by peshmerge** [EvanHerman/Timeline-Express#14]
Hi Evan, 

I have upgraded to the newest version of Timeline Express. I have noticed that the languages directory inside the plugin directory is missing. 

Thanks,
Peshmerge

**Comment by EvanHerman** [comment]
Hi Peshmerge,

That's correct. All translations are now handled through glotpress.

https://translate.wordpress.org/projects/wp-plugins/timeline-express

The translation file in the last version caused a lot of issues and prevented the options page from saving properly. You can see all the negative reviews in the repository due to it. 

Evan

That way anyone of our users

**Comment by peshmerge** [comment]
Hi Evan, 

Thanks for your fast replay. I didn't know that. But what should I do to get the correct translation? 

I noticed that because I didn't get the Dutch translation of the plugin while my site has Dutch language as a main language. [http://montium.nl]
You can see how beautiful Timeline Express is performing on our site :) 


PS: I am now contributing to the plugin by providing Arabic translation :) I have started this morning. 

Thanks,
Peshmerge

**Comment by EvanHerman** [comment]
Hi Peshmerge,

You can download any of the old language files from the WordPress.org repository:

https://wordpress.org/plugins/timeline-express/developers/

All previous versions are still available. Anything prior to v1.2 should have the language files you are looking for.

Thanks so much for beginning to contribute into translating things. Tons of others will certainly benefit from that - so thank you!


Evan
