### ISSUE TITLE
Option to always use local version of Font Awesome CSS

### ISSUE THREAD

**Issue by mattsims** [EvanHerman/timeline-express#23]
Currently, the plugin attempts to load a CDN-hosted copy of the Font Awesome CSS, and uses this version if available before falling back to the locally-hosted version.

It would be beneficial to be able to filter this choice so that the the local version can take priority over the CDN-hosted version, as if the CDN is slow then this holds up page render.

Happy to submit a PR if this is a reasonable request!

**Comment by mattsims** [comment]
I also note that if the local copy is used, the Font Awesome fonts appear to be missing from the folder anyway.

**Comment by EvanHerman** [comment]
Hey @mattsims,

Sorry for the delay in responding, been super busy on my end. Now that things have gotten back normal, I am going to take a look into this issue and push out any necessary patch. 

I will report back here when I have some additional info. 

Thanks!
Evan

**Comment by mattsims** [comment]
Awesome, thanks Evan!

**Comment by EvanHerman** [comment]
Hi @mattsims ,

I am pushing out an update now. To load the font awesome local version, instead of loading it via the CDN you can define the following constant in your themes <strong>functions.php</strong> file.

`define( 'TIMELINE_EXPRESS_FONT_AWESOME_LOCAL', true );`

That should work in both the free and pro versions of Timeline Express. Let me know if you are still facing issues after upgrading to 1.3.2 (free) or 1.3.0 (pro).

Thanks,
Evan

**Comment by mattsims** [comment]
Top man, thank you @Evan!
